package io.avalia.samba;

import org.junit.Assert;
import org.junit.Test;

/**
 * *** IMPORTANT WARNING : DO NOT EDIT THIS FILE ***
 * 
 * This file is used to specify what you have to implement. To check your work,
 * we will run our own copy of the automated tests. If you change this file,
 * then you will introduce a change of specification!!!
 * 
 * @author Olivier Liechti
 */
public class PandeiroTest {

	@Test
	public void thereShouldBeAnIInstrumentInterfaceAndAPandeiroClass() {
		IInstrument pandeiro = new Pandeiro();
		Assert.assertNotNull(pandeiro);
	}

	@Test
	public void itShouldBePossibleToPlayAnInstrument() {
		IInstrument pandeiro = new Pandeiro();
		String sound = pandeiro.play();
		Assert.assertNotNull(sound);
	}

	@Test
	public void aPandeiroShouldMakePaPa() {
		IInstrument pandeiro = new Pandeiro();
		String sound = pandeiro.play();
		Assert.assertEquals("papa", sound);
	}

	@Test
	public void aPandeiroShouldBeLouderThanAFlute() {
		IInstrument pandeiro = new Pandeiro();
		IInstrument flute = new Flute();
		int pandeiroVolume = pandeiro.getSoundVolume();
		int fluteVolume = flute.getSoundVolume();
		Assert.assertTrue(pandeiroVolume > fluteVolume);
	}

	@Test
	public void aTrumpetShouldBeGolden() {
		IInstrument trumpet = new Trumpet();
		String color = trumpet.getColor();
		Assert.assertEquals("golden", color);
	}

}
